### ISSUE TITLE
AWS glue job instance :[Errno 20] Not a directory

### ISSUE THREAD

**Issue by noodlze** [envkey/envkey-python#3] opened 2019-04-02 09:13 UTC
Hi,

I am trying to use envkey in my AWS Glue script. AWS sets up the running environment as a container. The ETL job only accepts one python file defining the job contents to be run so I have to pass the envkey + python-dotenv libraries contents as a zip. I am passing the envkey value as a param to the script and using the following function to load the envkey variables:

```
def load_envkey_values(envkey_value):
    import os
    os.environ['ENVKEY'] = envkey_value
    import envkey
    print("TESTING BQ_DATASET_TABLE:{}".format(os.environ['BQ_DATASET_TABLE']))
```

I am encountering [Errno 20] Not a directory:

```
Traceback (most recent call last):
File "script_2019-04-02-08-21-59.py", line 564, in <module>
main()
File "script_2019-04-02-08-21-59.py", line 491, in main
load_envkey_values(args['envkey'])
File "script_2019-04-02-08-21-59.py", line 151, in load_envkey_values
import envkey
File "/mnt/yarn/usercache/root/appcache/application_1554193162735_0001/container_1554193162735_0001_01_000001/libraries.zip/envkey/__init__.py", line 4, in <module>
File "/mnt/yarn/usercache/root/appcache/application_1554193162735_0001/container_1554193162735_0001_01_000001/libraries.zip/envkey/loader.py", line 25, in load
File "/mnt/yarn/usercache/root/appcache/application_1554193162735_0001/container_1554193162735_0001_01_000001/libraries.zip/envkey/fetch.py", line 46, in fetch_env
File "/usr/lib64/python2.7/subprocess.py", line 567, in check_output
process = Popen(stdout=PIPE, *popenargs, **kwargs)
File "/usr/lib64/python2.7/subprocess.py", line 711, in __init__
errread, errwrite)
File "/usr/lib64/python2.7/subprocess.py", line 1343, in _execute_child
raise child_exception
OSError: [Errno 20] Not a directory
```

Any help or explanation/insights into why this error occurred would be greatly appreciated.
... I am not even sure  if I can even use envkey with AWS glue...

**Comment by danenania** [comment] 2019-04-03 18:29
Hi,

I’m not too familiar with AWS Glue in particular, but it looks the problem is that the core `envkey-fetch` binary that this library wraps isn’t present where it should be in `envkey/ext/[platform]/envkey-fetch`. Can you see whether this is getting included in the zip file?

**Comment by noodlze** [comment] 2019-04-04 03:57
Hi, 

I checked and the binary is present for all the platforms(see the attached screenshot for all the contents of my zipped file). I installed envkey using pip, then copied the lib packages from  python 2.7 sites-packages 

 I don't know if it is any help, but I was able to use envkey with google cloud functions, which like AWS Glue manages the environment setup. The difference is that I was able to add the .env file because gcloud functions accepts a project folder ! Could it be due to the way that I am passing the envkey value?


![Screenshot 2019-04-04 10 50 38](https://user-images.githubusercontent.com/21037817/55528643-cd0a5d80-56c7-11e9-94ae-7dd51a9b07bc.png)

**Comment by danenania** [comment] 2019-04-04 05:32
If it was a problem with the `ENVKEY` value, you'd be getting a different error, so I think it must have something to do with loading the binary. 

Are you able to insert some some print statements in [envkey/fetch.py](https://github.com/envkey/envkey-python/blob/master/envkey/fetch.py) to see what's going on? If you could add a `print(path)` after line 40 like so:

```
def fetch_env(key, cache_enabled=False):
  path = __lib_path()
  print(path)
```

and then run it again on Glue, that might help to see what's going wrong.

**Comment by noodlze** [comment] 2019-04-04 08:19
Hi,
This was the path returned: 
/mnt/yarn/usercache/root/appcache/application_1554362447388_0001/container_1554362447388_0001_01_000001/Archive.zip/envkey/ext/envkey-fetch_1.2.4_linux_amd64/envkey-fetch

**Comment by danenania** [comment] 2019-04-04 20:03
Ok, I think the problem may be that the zip file isn't getting uncompressed, which doesn't play well with `subprocess` executing the binary. Looking at the [AWS Glue docs](https://docs.aws.amazon.com/glue/latest/dg/aws-glue-programming-python-libraries.html), it seems this might be by design:

```
You can use Python extension modules and libraries with your AWS Glue ETL scripts as long as they are written in pure Python. C libraries such as pandas are not supported at the present time, nor are extensions written in other languages.
```

It's not 100% clear to me whether "extensions written in other languages" includes executing an embedded binary as envkey does, but that would explain the problem. Perhaps AWS support could confirm/deny whether this is possible?

**Comment by danenania** [comment] 2019-04-10 19:59
Closing this under the assumption that AWS Glue cannot execute the bundled `envkey-fetch` binary. Please re-open if you find out otherwise!

**Closed as completed by danenania** 2019-04-10 19:59 UTC
